#!/usr/bin/env python3
"""
scripts/gen_config.py
Generates DEM config files for the Makefile targets.
All parameters have sensible defaults matching the assignment.
"""
import argparse, os

TEMPLATE = """\
# Auto-generated by gen_config.py
lx = {lx}
ly = {ly}
lz = {lz}
gx = 0.0
gy = 0.0
gz = {gz}
kn      = 1.0e5
gamma_n = {gamma}
dt      = {dt}
t_final = {t_final}
n_particles          = {n}
particle_r           = 0.02
particle_m           = 1.0
n_threads            = {threads}
output_interval      = {out_int}
max_traj_particles   = {maxtraj}
init_mode            = {mode}
random_seed          = 42
"""

MODE_DEF = {
    1: dict(gz=-9.81, lz=1.0, t_final=0.3,  out_int=5e-3,  maxtraj=500),
    2: dict(gz=-9.81, lz=1.0, t_final=0.4,  out_int=1e-4,  maxtraj=1),
    3: dict(gz=-9.81, lz=1.0, t_final=2.0,  out_int=5e-4,  maxtraj=1),
    4: dict(gz=0.0,   lz=10., t_final=0.5,  out_int=1e-4,  maxtraj=1),
}

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--n',       type=int,   default=200)
    p.add_argument('--threads', type=int,   default=4)
    p.add_argument('--mode',    type=int,   default=1)
    p.add_argument('--gamma',   type=float, default=50.0)
    p.add_argument('--dt',      type=float, default=1e-5)
    p.add_argument('--t_final', type=float, default=None)
    p.add_argument('--gz',      type=float, default=None)
    p.add_argument('--lx',      type=float, default=1.0)
    p.add_argument('--ly',      type=float, default=1.0)
    p.add_argument('--lz',      type=float, default=None)
    p.add_argument('--out_int', type=float, default=None)
    p.add_argument('--maxtraj', type=int,   default=None)
    p.add_argument('--output',  type=str,   default='configs/run.cfg')
    args = p.parse_args()

    d = MODE_DEF.get(args.mode, MODE_DEF[1]).copy()
    if args.t_final is not None: d['t_final'] = args.t_final
    if args.gz      is not None: d['gz']      = args.gz
    if args.lz      is not None: d['lz']      = args.lz
    if args.out_int is not None: d['out_int'] = args.out_int
    if args.maxtraj is not None: d['maxtraj'] = args.maxtraj

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, 'w') as f:
        f.write(TEMPLATE.format(
            n=args.n, threads=args.threads, mode=args.mode,
            gamma=args.gamma, dt=args.dt,
            lx=args.lx, ly=args.ly, **d
        ))
    print(f"[gen_config] {args.output}  N={args.n} T={args.threads} mode={args.mode} gamma={args.gamma} dt={args.dt}")

if __name__ == '__main__':
    main()
